# Generated by Django 3.1.3 on 2020-11-21 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shab_num', models.IntegerField()),
                ('shab_year', models.IntegerField()),
                ('shab_markaz', models.IntegerField()),
                ('shab_mosalsal', models.IntegerField()),
                ('shab_name', models.CharField(max_length=255)),
                ('shab_city', models.CharField(max_length=64)),
                ('medical_dec', models.CharField(max_length=64)),
                ('note_type', models.CharField(max_length=64)),
                ('shab_image', models.FileField(upload_to='shakawi_data/%Y/%m/%d')),
                ('date_recored', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
