# Generated by Django 3.0.2 on 2020-12-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shab',
            name='rays',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shab',
            name='reports',
            field=models.CharField(default='', max_length=64),
        ),
    ]
