# Generated by Django 3.0.2 on 2021-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0002_auto_20201228_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=128)),
            ],
        ),
    ]
