# Generated by Django 3.0.2 on 2021-02-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0003_medicaldec_notetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldec',
            old_name='note',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='notetype',
            old_name='note',
            new_name='name',
        ),
    ]
