# Generated by Django 3.0.2 on 2021-02-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0004_auto_20210211_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldec',
            old_name='name',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='notetype',
            old_name='name',
            new_name='note',
        ),
    ]
