# Generated by Django 3.0.2 on 2021-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0005_auto_20210211_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldec',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
