# Generated by Django 3.0.2 on 2021-02-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0006_medicaldec_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldec',
            name='name',
        ),
    ]
