# Generated by Django 3.0.2 on 2021-02-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0008_medicaldecision_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldecision',
            old_name='name',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
