# Generated by Django 3.0.2 on 2021-02-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0011_auto_20210211_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='name',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='note_type',
            old_name='name',
            new_name='note',
        ),
    ]
