# Generated by Django 3.0.2 on 2021-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0012_auto_20210211_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='g_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note_type',
            name='g_id',
            field=models.IntegerField(default=0),
        ),
    ]
