# Generated by Django 3.0.2 on 2021-02-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakawi', '0013_auto_20210211_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalDec',
        ),
        migrations.DeleteModel(
            name='NoteType',
        ),
    ]
